### PR TITLE
Use hubot-bugzilla for show bug details. Fixes #1

### LINKED ISSUE #1: Provide useful information when a Bugzilla bug number is mentioned
When a Bugzilla bug number is mentioned in the channel, the bot should provide a link to the bug, the importance, status, assignee, and summary.

Example conversation:
> davehunt: Hey Bob, check out bug 689423
> webqabot: Bug https://bugzilla.mozilla.org/show_bug.cgi?id=689423 normal, NEW , Add Angry Birds to Firefox new tab page

Let's try to write this as an external script so that other users of Hubot can use it. This will require at least a way to configure the Bugzilla instance to query.

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@davehunt This looks good in terms of including an external script. Did you want me to take a look at `hubot-bugzilla` as well? I guess not as it's already been deployed to npm.  I will configure the heroku app to allow for review apps so we can easily test this.

**Comment by bobsilverberg** [comment]
@davehunt Okay, I set things up for review apps, but you'll need to rebase this to pick up my latest commit in order to create a review app for it. Do you mind doing that so we can test the workflow?

**Comment by davehunt** [comment]
Sure I can do that. After writing this, I realised we could just invite firebot or bugbot into our channel, and they would probably do a better job than reimplementing their features. :)

**Comment by davehunt** [comment]
Rebased.

**Comment by bobsilverberg** [comment]
I made a mistake in the app.json file that I committed to the repo, which ended up generating an invalid irc nick. I am trying to experiment and fix this now, but the Heroku API is down do I cannot. Just a heads up for you.

**Comment by bobsilverberg** [comment]
We tested with the review app and it seems to work well. Thanks @davehunt!

**Pull request merged**
